package com.killer.automation.service

import android.accessibilityservice.AccessibilityService
import android.os.SystemClock
import android.view.accessibility.AccessibilityEvent
import android.view.accessibility.AccessibilityNodeInfo
import com.killer.automation.data.EncryptedDataManager
import com.killer.automation.engine.DecisionEngine
import com.killer.automation.model.Offer
import dagger.hilt.android.AndroidEntryPoint
import timber.log.Timber
import javax.inject.Inject

/**
 * AccessibilityService that intercepts screen content and forwards offers to the DecisionEngine.
 * Lightweight: parsing only the view tree and delegating heavy decisions to DecisionEngine.
 */
@AndroidEntryPoint
class GestureInterceptor : AccessibilityService() {

    @Inject
    lateinit var decisionEngine: DecisionEngine

    @Inject
    lateinit var encryptedDataManager: EncryptedDataManager

    // Timestamp of the last action we performed to avoid processing events generated by our own clicks
    private var lastActionByBotTimestamp: Long = 0L
    private val botActionDebounceMs = 1000L

    override fun onServiceConnected() {
        super.onServiceConnected()
        Timber.i("GestureInterceptor connected")
    }

    override fun onAccessibilityEvent(event: AccessibilityEvent?) {
        if (event == null) return

        // Lightweight early checks
        try {
            val now = SystemClock.uptimeMillis()
            if (now - lastActionByBotTimestamp < botActionDebounceMs) {
                // Recent action produced by the bot — skip to avoid loops
                Timber.d("Skipping event because it is too close to our last action")
                return
            }

            val root = rootInActiveWindow ?: run {
                Timber.d("rootInActiveWindow is null")
                return
            }

            // Find an active offer in the UI tree
            val offer = findActiveOffer(root)

            if (offer != null) {
                Timber.d("Detected offer: %s", offer)

                // Security: check subscription validity
                if (!encryptedDataManager.isSubscriptionValid()) {
                    Timber.w("Subscription invalid — will not perform actions")
                    root.recycle()
                    return
                }

                // Delegate decision-making to DecisionEngine (must be fast / local)
                val result = decisionEngine.evaluateOffer(offer)

                if (result.shouldAccept) {
                    Timber.i("DecisionEngine recommended accepting the offer")

                    // Try to find the accept button (by id or text) and click it
                    val clicked = clickAcceptButton(root)

                    if (clicked) {
                        lastActionByBotTimestamp = SystemClock.uptimeMillis()
                        Timber.i("Clicked accept button for offer: %s", offer)
                    } else {
                        Timber.w("Could not find clickable accept button for offer: %s", offer)
                    }
                } else {
                    Timber.i("DecisionEngine recommended rejecting the offer")
                }
            }

            root.recycle()

        } catch (t: Throwable) {
            Timber.e(t, "Error while processing accessibility event")
        }
    }

    override fun onInterrupt() {
        Timber.i("GestureInterceptor interrupted")
    }

    // Attempts to locate an active offer in the tree and extract an Offer model
    private fun findActiveOffer(root: AccessibilityNodeInfo): Offer? {
        // Heuristics: try known resource IDs first (if you know them), then fallback to text-based search
        // NOTE: Replace resource-id strings below with the real ones for your target app if available
        val possiblePriceIds = listOf(
            "com.example.app:id/offer_price",
            "com.rideshare.app:id/price",
            "price"
        )
        val possibleDistanceIds = listOf(
            "com.example.app:id/offer_distance",
            "com.rideshare.app:id/distance",
            "distance"
        )
        val possibleOfferContainers = listOf(
            "com.example.app:id/offer_container",
            "offer_container",
            "offer_card"
        )

        // Try to locate a container node for an active offer
        var containerNode: AccessibilityNodeInfo? = null
        for (id in possibleOfferContainers) {
            containerNode = findNodeByViewId(root, id)
            if (containerNode != null) break
        }

        // Fallback: search for text that suggests an active offer (e.g., "New ride", "Oferta", "Aceptar")
        if (containerNode == null) {
            containerNode = findNodeByText(root, listOf("Nuevo viaje", "New ride", "Oferta", "Offer")).also {
                if (it != null) Timber.d("Found offer container by text fallback")
            }
        }

        if (containerNode == null) return null

        try {
            // Extract price
            var priceText: String? = null
            for (id in possiblePriceIds) {
                priceText = findNodeByViewId(containerNode, id)?.text?.toString()
                if (!priceText.isNullOrBlank()) break
            }
            if (priceText.isNullOrBlank()) {
                priceText = findNodeByText(containerNode, listOf("€", "$", "USD", "EUR"))?.text?.toString()
            }

            // Extract distance
            var distanceText: String? = null
            for (id in possibleDistanceIds) {
                distanceText = findNodeByViewId(containerNode, id)?.text?.toString()
                if (!distanceText.isNullOrBlank()) break
            }
            if (distanceText.isNullOrBlank()) {
                distanceText = findNodeByText(containerNode, listOf("km", "miles", "mi"))?.text?.toString()
            }

            // Create Offer model if we have enough info
            if (!priceText.isNullOrBlank() || !distanceText.isNullOrBlank()) {
                // Parse values conservatively — DecisionEngine can do further normalization
                val offer = Offer(
                    priceRaw = priceText ?: "",
                    distanceRaw = distanceText ?: "",
                    // Additional fields can be extracted similarly if Models.kt defines them
                )
                return offer
            }

            return null

        } finally {
            containerNode.recycle()
        }
    }

    // Finds a node by fully-qualified view id (resource id) — returns first match
    private fun findNodeByViewId(root: AccessibilityNodeInfo, viewId: String): AccessibilityNodeInfo? {
        return try {
            // viewId may be just the id (e.g. "price") or full ("com.pkg:id/price"). Try both via text search and viewIdResourceName.
            val byId = root.findAccessibilityNodeInfosByViewId(viewId)
            if (byId.isNullOrEmpty()) null else byId[0]
        } catch (e: Exception) {
            // findAccessibilityNodeInfosByViewId can throw if viewId not in expected format
            null
        }
    }

    // Finds first node that contains any of the supplied texts (case-insensitive)
    private fun findNodeByText(root: AccessibilityNodeInfo, texts: List<String>): AccessibilityNodeInfo? {
        for (t in texts) {
            val nodes = root.findAccessibilityNodeInfosByText(t)
            if (!nodes.isNullOrEmpty()) return nodes[0]
        }
        return null
    }

    // Attempts to find an "Accept" button inside the tree and click it
    private fun clickAcceptButton(root: AccessibilityNodeInfo): Boolean {
        // Known ids/texts for an accept button — replace with real ones if you know them
        val possibleAcceptIds = listOf(
            "com.example.app:id/accept_button",
            "com.rideshare.app:id/accept",
            "accept_button"
        )
        val possibleAcceptTexts = listOf("Aceptar", "Accept", "CONFIRM", "Confirmar")

        // Try ids first
        for (id in possibleAcceptIds) {
            val node = findNodeByViewId(root, id)
            if (node != null && performClickOnNode(node)) return true
        }

        // Then try by text
        for (txt in possibleAcceptTexts) {
            val node = findNodeByText(root, listOf(txt))
            if (node != null && performClickOnNode(node)) return true
        }

        // Fallback: search for clickable nodes inside the offer container
        val clickable = findFirstClickable(root)
        if (clickable != null) {
            return performClickOnNode(clickable)
        }

        return false
    }

    // Performs a click on the node or its clickable ancestor
    private fun performClickOnNode(node: AccessibilityNodeInfo): Boolean {
        try {
            if (node.isClickable) {
                val ok = node.performAction(AccessibilityNodeInfo.ACTION_CLICK)
                Timber.d("Performed click on node: %s — success=%s", node.viewIdResourceName ?: node.text, ok)
                return ok
            }

            // climb up to find clickable parent
            var parent = node.parent
            while (parent != null) {
                if (parent.isClickable) {
                    val ok = parent.performAction(AccessibilityNodeInfo.ACTION_CLICK)
                    Timber.d("Performed click on parent node: %s — success=%s", parent.viewIdResourceName ?: parent.text, ok)
                    parent.recycle()
                    return ok
                }
                val next = parent.parent
                parent.recycle()
                parent = next
            }
        } catch (t: Throwable) {
            Timber.e(t, "Error performing click on node")
        } finally {
            node.recycle()
        }
        return false
    }

    // Breadth-first search for first clickable node under root
    private fun findFirstClickable(root: AccessibilityNodeInfo): AccessibilityNodeInfo? {
        val queue: ArrayDeque<AccessibilityNodeInfo> = ArrayDeque()
        queue.add(root)
        while (queue.isNotEmpty()) {
            val n = queue.removeFirst()
            if (n.isClickable) return n
            for (i in 0 until n.childCount) {
                val child = n.getChild(i)
                if (child != null) queue.add(child)
            }
        }
        return null
    }
}
