android.useAndroidX=true
android.enableJetifier=true
android.compileSdk=35
android.targetSdk=35
android.minSdk=28

kotlin.jvmTarget=21
kotlin.code.style=official

org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=512m
org.gradle.parallel=true
org.gradle.caching=true

android.suppressUnsupportedCompileSdk=35
